"""add tenant_id to knowledge_docs and conversations

Revision ID: 1ab18806c2f9
Revises: 1c0c2afea11a
Create Date: 2026-08-29 17:06:27.081276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab18806c2f9'
down_revision: Union[str, Sequence[str], None] = '1c0c2afea11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False))
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.add_column('knowledge_docs', sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False))
    op.create_index(op.f('ix_knowledge_docs_tenant_id'), 'knowledge_docs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_docs_tenant_id'), table_name='knowledge_docs')
    op.drop_column('knowledge_docs', 'tenant_id')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_column('conversations', 'tenant_id')
    # ### end Alembic commands ###
